name: intra_42
description: Intra 42 app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.0+2dev

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:

  #icons
  flutter_launcher_icons: ^0.11.0

  #loading
  loading_animation_widget: ^1.2.0+3

  #brotli
  flutter_brotli: ^0.0.2

  #notifications
  flutter_local_notifications: ^12.0.4

  #background worker
  workmanager: ^0.5.1

  #url launcher
  url_launcher: ^6.1.5

  image: ^3.2.2

  #web socket
  web_socket_channel: ^2.2.0

  #parse html
  html: ^0.15.1

  #click canvas
  touchable: ^1.0.2

  #webview
  flutter_inappwebview: ^5.3.2

  #path
  path_provider: ^2.0.11

  #connection state
  connectivity_plus: ^2.3.8

  #fonts
  google_fonts: ^3.0.1

  #internationalization
  intl: ^0.17.0

  #image
  extended_image: ^6.3.0
  flutter_svg: ^1.1.4

  #logging
  logger: any

  #network
  dio: ^4.0.6
  retrofit: ^3.0.1+1

  #local storage
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  shared_preferences: ^2.0.8

  #state manager
  flutter_riverpod: ^2.0.1

  #string format
  sprintf: ^6.0.2

  #
  timeago: ^3.3.0

  #calendar
  syncfusion_flutter_calendar: ^20.3.56

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.7.0

dev_dependencies:
  #code generator
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  retrofit_generator: ^4.0.3+1
  build_runner: ^2.2.0
  isar_generator: ^3.0.2
  #json
  json_serializable: ^6.3.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  android: "icons"
  ios: true
  image_path: "assets/img/logo.png"
  remove_alpha_ios: true


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/
    - assets/
    - fonts/
  fonts:
    - family: PtSans
      fonts:
        - asset: assets/fonts/ptsans_narrow_bold.ttf
    - family: helve
      fonts:
        - asset: fonts/helvetica.ttf

flutter_intl:
  enabled: true
  arb-dir: translation
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart
  output-class: AppLocalizations